name: simswap
channels:
  - pytorch
  - defaults
dependencies:
  - pip=20.2.4
  - python=3.6
  - pytorch=1.7.0
  - torchaudio=0.7
  - torchvision=0.8.0
  - cudatoolkit=11.0
  - pip:
    - insightface==0.2.1
    - onnxruntime==1.8.0
    - moviepy==1.0.3
    - tqdm==4.43.0
    - Flask==1.1.2
    - sqlalchemy==1.3.22
    - flask-restful==0.3.8
    - Flask-SQLAlchemy==2.4.4
    - flask-marshmallow==0.14.0
    - marshmallow-sqlalchemy==0.24.1
    - gunicorn==20.1.0
